const Contact = () => {
  return (
    <div className="p-4 border rounded-lg bg-white dark:bg-gray-900">
      <h2 className="text-xl font-semibold">Contact</h2>
      <p className="text-gray-500 dark:text-gray-400 text-sm">Generated by next-temp</p>
    </div>
  );
}

export default Contact;
