
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/lib/theme-provider";

export const metadata = {
  title: "Generated App",
  description: "Generated by my-cli",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className="bg-white text-black dark:bg-[#0b0f14] dark:text-white">
      <body className="min-h-screen flex flex-col">
        <ThemeProvider>
          <Navbar />
          <main className="flex-1 container mx-auto px-6 py-10">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

export default Layout;
